### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by OrigamingWasTaken** [MiningTcup/Roblox-Multi-Instance#10]
I tried downloading the osx build and running it in the terminal (`chmod +x multi_instances_binary`).
This is what it looks like:
![CleanShot 2024-06-20 at 21 42 43@2x](https://github.com/MiningTcup/Roblox-Multi-Instance/assets/74014262/786c3396-d318-49bf-a042-12f99139edf2)

I launched roblox twice from the website, and the second time, it closed the first instance.

**Comment by MiningTcup** [comment]
Yea, someone else said that too. Sadly I don't have a Mac so I can't do any testing, and my guess of what might work was wrong. I'm going to be removing the Mac/Linux release. Sorry :(

**Comment by OrigamingWasTaken** [comment]
Hey, I think i've found a way to make it work.
I've found another project that does it. Basically, you open roblox and force it to quit.
Here's a link to working code: https://github.com/iamEvanYT/MacRobloxUtility/blob/main/utils/roblox.py#L11

**Comment by MiningTcup** [comment]
Oh neat. Thanks!

**Comment by Avaluate** [comment]
Just an additional comment (as I am the original creator of this program, MainDabRblx is my old account): the way these threading things work with mutex is totally different from Windows and MacOS... so don't worry too much about that

**Comment by OrigamingWasTaken** [comment]
> Just an additional comment (as I am the original creator of this program, MainDabRblx is my old account): the way these threading things work with mutex is totally different from Windows and MacOS... so don't worry too much about that

It's to be expected... You can implement the solution I provided if you want but that's your choice.
