### ISSUE TITLE
why does the file find my language while running?

### ISSUE THREAD

**Issue by MHMHMHM121H** [MiningTcup/Roblox-Multi-Instance#13]
.

**Comment by smoressy** [comment]
rat prolly

**Comment by MiningTcup** [comment]
On what tester?

**Comment by MiningTcup** [comment]
The code I wrote does not detect your language. This does not mean, however, that DOTNET won't. I suggest you compile it yourself. If you complain any more, I will assume you are a scammer.

https://www.virustotal.com/gui/file/569df3da9319a9ae298c37dffeb98c861bd773a513d99091d02f44cca3d945c2/detection
