### ISSUE TITLE
This is a Virus (Read)

### ISSUE THREAD

**Issue by smoressy** [MiningTcup/Roblox-Multi-Instance#14]
https://tria.ge/240805-zbb8ps1eqf/behavioral1

No wonder why this was updated so recently...

**Comment by MiningTcup** [comment]
I'm sorry, compile it yourself. My program does nothing mentioned in that report, but DOTNET might. I believe you are a scammer and will be blocking you from posting further issues.

Compile it yourself. It's not that hard. Or just stop playing Roblox. :skull:
