### ISSUE TITLE
No .exe asset

### ISSUE THREAD

**Issue by negativezero001** [MiningTcup/Roblox-Multi-Instance#9]
I watch the video tutorial, and it shows to download the asset "roblox-multi-instance.exe" but there are only 2 assets for me, the .zip file and the .tar file, so I am unable to download the .exe

**Comment by MiningTcup** [comment]
Sorry for the confusion! The exe (and the other exe) are both contained within the ZIP.

**Comment by MiningTcup** [comment]
Oops, I got confused! Wrong version, fixed now!
